export default function AboutUs() {
    return (
        <div className="text-[20px] bold flex w-auto text-center">
            FUNDADO PELOS DJS E PRODUTORES GOIANOS DÁRIO CASTRO E HIGOR SALES, O SUPER SÁBADO VEM COM O INTUITO DE ESTIMULAR A MÚSICA ELETRÔNICA NA NOSSA CAPITAL. INICIADO COMO UM ROLE ENTRE AMIGOS, O SUPER SÁBADO VEM EVOLUINDO E DESENVOLVENDO, PASSANDO PELO TECHNO AO TECH HOUSE, MAS SEMPRE MANTENDO
            OS VALORES MAIS VERDADEIROS DA HOUSE MUSIC EM SEU NÚCLEO CRIATIVO. VAMOS FORTALECER O MOVIMENTO
        </div>
    );
}
